server:
  port: 8095
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.110.52.14:3306/jtdb?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456

#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true  
#引入日志信息
logging:
  level: 
    com.jt.mapper: debug

#dubbo配置    
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: provider-order
  registry:
    address: zookeeper://47.110.52.14:2181?backup=47.110.52.14:2182,47.110.52.14:2183
  protocol:
    name: dubbo
    port: 20883