server:
  port: 8092
  servlet:
    context-path: /
spring:     #定义springmvc视图解析器
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      #web项目不应该有数据源，但是没办法，必须有，后面再处理吧
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.110.52.14:3306/jtdb?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
  #web项目不用数据源
dubbo:
  scan:
    base-packages: com.jt
  application:
    name: comsumer-web
  registry:
    address: zookeeper://47.110.52.14:2181?backup=47.110.52.14:2182,47.110.52.14:2183
